version: '3.9'

services:
    website:
      build:
          context: .
          dockerfile: Dockerfile
      env_file:
        - .env
      ports:
        - '8000:80'
      networks:
        - helltfbot-v2_default
networks:
  helltfbot-v2_default:
    external: true
