name: deploy

on:
  push:
    branches: ['main']

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
        env:
          VITE_ENV: prod
          VITE_TWITCH_LOGIN: https://id.twitch.tv/oauth2/authorize?response_type=code&client_id=b6uhkaukifr993zprguyesbminengw&redirect_uri=http://localhost:3000/callback&scope=user%3Aread%3Aemail
          VITE_TWITCH_CLIENT_ID: ${{ secrets.TWITCH_ID }}
          VITE_TWITCH_CLIENT_SECRET: ${{ secrets.TWITCH_SECRET }}
